# Generated by Django 5.1 on 2024-09-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('thumbnails1', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('thumbnails2', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('thumbnails3', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('thumbnails4', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('duration', models.DurationField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('launch_screen', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('type', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('python', 'Python')], max_length=64)),
            ],
        ),
    ]
